<a href="https://colab.research.google.com/github/T-Svitlichna/Analysis_Cafe_Sales/blob/main/EDA_Cafe_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Analysis Cafe Sales
Cafe Sales - Dirty Data Cleaning Training

**Overview**

**.File Information**

.File Name: dirty_cafe_sales.csv

.Number of Rows: 10,000

.Number of Columns: 8

|Column name | Dedcription| Example Value|
-------------|------------|--------------|
|Transaction ID|	A unique identifier for each transaction. Always present and unique. |TXN_1234567|
|Item|	The name of the item purchased. May contain missing or invalid values (e.g., "ERROR").	|Coffee, Sandwich|
|Quantity|	The quantity of the item purchased. May contain missing or invalid values.	|1, 3, UNKNOWN|
|Price Per Unit|	The price of a single unit of the item. May contain missing or invalid values.	|2.00, 4.00|
|Total Spent|	The total amount spent on the transaction. Calculated as Quantity * Price Per Unit.|	8.00, 12.00|
|Payment Method|	The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN").	|Cash, Credit Card|
|Location|	The location where the transaction occurred. May contain missing or invalid values.	|In-store, Takeaway|
|Transaction Date|	The date of the transaction. May contain missing or incorrect values.	|2023-01-01|

!pip install numpy pandas matplotlib

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df_origin = pd.read_csv('https://raw.githubusercontent.com/T-Svitlichna/Analysis_Cafe_Sales/refs/heads/main/data/dirty_cafe_sales.csv')

df_origin.head()
df = df_origin.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

#Primary diagnosis

In [3]:
df = df_origin.copy()
df.head()
print("Data types (raw):\n")
df.dtypes

Data types (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem:
- Numeric columns(Quantity, Price Pre Unit, Total Spend)
- Date columns (Transaction Date)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

Missing values

In [5]:
print("Missing values:\n")
missing = df.isnull().sum()
missing_pct = (missing/len(df) * 100).round(2)
missing_rep = pd.DataFrame({
    "count": missing,
    "%": missing_pct
})
print(missing_rep)
missing_rep[missing_rep["%"] > 0]

Missing values:

                  count      %
Transaction ID        0   0.00
Item                333   3.33
Quantity            138   1.38
Price Per Unit      179   1.79
Total Spent         173   1.73
Payment Method     2579  25.79
Location           3265  32.65
Transaction Date    159   1.59

                  count      %
Item                333   3.33
Quantity            138   1.38
Price Per Unit      179   1.79
Total Spent         173   1.73
Payment Method     2579  25.79
Location           3265  32.65
Transaction Date    159   1.59

In [6]:
print("Unique value:\n")
print(df["Item"].value_counts(dropna=False))
print
print("--- Item ---\n")
print(df["Payment Method"].value_counts(dropna=False))
print("--- PAy Metod  ---\n")
print(df["Location"].value_counts(dropna=False))
print("--- Location ---\n")

Unique value:

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64
--- Item ---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64
--- PAy Metod  ---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64
--- Location ---

In [10]:
print("Find lines with 'Error" or 'UNKNOW')
masr_er = df.isin(['ERROR', 'UNKNOWN']).any(axis=1)
print(f"Number of lines with 'Error' or 'UNKNOWN': {masr_er.value_counts()[True]}")
print(f"Number of lines without 'Error' or 'UNKNOWN': {masr_er.value_counts()[False]}")
print(df.groupby()[masr_er])

Find lines with 'Error
Number of lines with 'Error' or 'UNKNOWN': 2845
Number of lines without 'Error' or 'UNKNOWN': 7155

TypeError: You have to supply one of 'by' and 'level'

ДЗ True/False  замінити фицрами по кожному значенню

## Date cleaning

In [9]:
print("Rename columns:\n")
#df.columns = df.str.strip()
df = df.rename(columns={'Transaction ID':'transaction_id',
                        'Item':'item',
                        'Quantity':'quantity',
                        'Price Per Unit':'price_per_unit',
                        'Total Spent':'total_spent',
                        'Payment Method':'payment_method',
                        'Location':'location',
                        'Transaction Date':'transaction_date',
      })
print(list(df.columns))

Rename columns:

['transaction_id', 'item', 'quantity', 'price_per_unit', 'total_spent', 'payment_method', 'location', 'transaction_date']

In [12]:
#'ERROR'/'UNKNOW -> NaN
df.replace(['ERROR', 'UNKNOWN', 'error', 'unknown', ' '], np.nan, inplace=True)
df.head()

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-store,2023-06-11

In [11]:
# Converting numeric and Date ->columns
for col in ['quantity', 'price_per_unit', 'total_spent']:
    df[col] = pd.to_numeric(df[col], errors='coerce')
df.dtypes

transaction_id       object
item                 object
quantity            float64
price_per_unit      float64
total_spent         float64
payment_method       object
location             object
transaction_date     object
dtype: object

In [13]:
df["transaction_date"] = pd.to_datetime(df['transaction_date'], errors='coerce')
df['transaction_date']

0      2023-09-08
1      2023-05-16
2      2023-07-19
3      2023-04-27
4      2023-06-11
          ...
9995   2023-08-30
9996   2023-06-02
9997   2023-03-02
9998   2023-12-02
9999   2023-11-07
Name: transaction_date, Length: 10000, dtype: datetime64[ns]

In [14]:
print('onverting columns:\n')
df.dtypes

onverting columns:

transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
dtype: object

In [18]:
print(df.isna().sum())

transaction_id         0
item                 969
quantity             479
price_per_unit       533
total_spent          502
payment_method      3178
location            3961
transaction_date     460
dtype: int64

04062026

In [24]:
for col in['item', 'payment_method', 'location']:
 df[col] = df[col].str.strip().str.title()
print('Text fields are standartized (Title Case)')
df

Text fields are standartized (Title Case)

,transaction_id,item,quantity,price_per_unit,total_spent,payment_method,location,transaction_date
0,TXN_1961373,Coffee,2.0,2.0,4.0,Credit Card,Takeaway,2023-09-08
1,TXN_4977031,Cake,4.0,3.0,12.0,Cash,In-Store,2023-05-16
2,TXN_4271903,Cookie,4.0,1.0,NaN,Credit Card,In-Store,2023-07-19
3,TXN_7034554,Salad,2.0,5.0,10.0,NaN,NaN,2023-04-27
4,TXN_3160411,Coffee,2.0,2.0,4.0,Digital Wallet,In-Store,2023-06-11
...,...,...,...,...,...,...,...,...
9995,TXN_7672686,Coffee,2.0,2.0,4.0,NaN,NaN,2023-08-30
9996,TXN_9659401,NaN,3.0,NaN,3.0,Digital Wallet,NaN,2023-06-02
9997,TXN_5255387,Coffee,4.0,2.0,8.0,Digital Wallet,NaN,2023-03-02
9998,TXN_7695629,Cookie,3.0,NaN,3.0,Digital Wallet,NaN,2023-12-02
9999,TXN_6170729,Sandwich,3.0,4.0,12.0,Cash,In-Store,2023-11-07

## Cleaning results

In [33]:
# df_origin = name_your origin_ DataFrame
#df = name_your_clean_DataFrame
print("Cleaning results:\n")
print(f"Rows before:{len(df_origin)}")
print(f"Rows after{len(df)}")
print(f"Loss:{len(df_origin) - len(df)} ({(len(df_origin) - len(df)) / len(df_origin) * 100:.1f}%)")
print("\nResidual gaps")
remaining = df.isna().sum()
print(remaining[remaining > 0] if remaining.any() else "No gaps")
print("Data types after clenup:")
print("=" *35)
print(df.dtypes)
print("\nStatistic")
print("=" *35)
print(df[["quantity", "price_per_unit", "total_spent"]].describe().round(2))

Cleaning results:

Rows before:10000
Rows after10000
Loss:0 (0.0%)

Residual gaps
item                 969
quantity             479
price_per_unit       533
total_spent          502
payment_method      3178
location            3961
transaction_date     460
dtype: int64
Data types after clenup:
===================================
transaction_id              object
item                        object
quantity                   float64
price_per_unit             float64
total_spent                float64
payment_method              object
location                    object
transaction_date    datetime64[ns]
dtype: object

Statistic
===================================
       quantity  price_per_unit  total_spent
count   9521.00         9467.00      9498.00
mean       3.03            2.95         8.92
std        1.42            1.28         6.01
min        1.00            1.00         1.00
25%        2.00            2.00         4.00
50%        3.00            3.00         8.00
75%        4.00            4.00        12.00
max        5.00            5.00        25.00