<a href="https://colab.research.google.com/github/T-Svitlichna/Analysis_Cafe_Sales/blob/main/EDA_Cafe_Sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Analysis Cafe Sales
Cafe Sales - Dirty Data Cleaning Training

**Overview**

**.File Information**

.File Name: dirty_cafe_sales.csv

.Number of Rows: 10,000

.Number of Columns: 8

|Column name | Dedcription| Example Value|
-------------|------------|--------------|
|Transaction ID|	A unique identifier for each transaction. Always present and unique. |TXN_1234567|
|Item|	The name of the item purchased. May contain missing or invalid values (e.g., "ERROR").	|Coffee, Sandwich|
|Quantity|	The quantity of the item purchased. May contain missing or invalid values.	|1, 3, UNKNOWN|
|Price Per Unit|	The price of a single unit of the item. May contain missing or invalid values.	|2.00, 4.00|
|Total Spent|	The total amount spent on the transaction. Calculated as Quantity * Price Per Unit.|	8.00, 12.00|
|Payment Method|	The method of payment used. May contain missing or invalid values (e.g., None, "UNKNOWN").	|Cash, Credit Card|
|Location|	The location where the transaction occurred. May contain missing or invalid values.	|In-store, Takeaway|
|Transaction Date|	The date of the transaction. May contain missing or incorrect values.	|2023-01-01|

!pip install numpy pandas matplotlib

In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
df_origin = pd.read_csv('https://raw.githubusercontent.com/T-Svitlichna/Analysis_Cafe_Sales/refs/heads/main/data/dirty_cafe_sales.csv')

df_origin.head()
df = df_origin.copy()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

#Primary diagnosis

In [13]:
df = df_origin.copy()
df.head()
print("Data types (raw):\n")
df.dtypes

Data types (raw):

Transaction ID      object
Item                object
Quantity            object
Price Per Unit      object
Total Spent         object
Payment Method      object
Location            object
Transaction Date    object
dtype: object

Problem:
- Numeric columns(Quantity, Price Pre Unit, Total Spend)
- Date columns (Transaction Date)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    10000 non-null  object
 1   Item              9667 non-null   object
 2   Quantity          9862 non-null   object
 3   Price Per Unit    9821 non-null   object
 4   Total Spent       9827 non-null   object
 5   Payment Method    7421 non-null   object
 6   Location          6735 non-null   object
 7   Transaction Date  9841 non-null   object
dtypes: object(8)
memory usage: 625.1+ KB

Missing values

In [22]:
print("Missing values:\n")
missing = df.isnull().sum()
missing_pct = (missing/len(df) * 100).round(2)
missing_rep = pd.DataFrame({
    "count": missing,
    "%": missing_pct
})
print(missing_rep)
missing_rep[missing_rep["%"] > 0]

Missing values:

                  count      %
Transaction ID        0   0.00
Item                333   3.33
Quantity            138   1.38
Price Per Unit      179   1.79
Total Spent         173   1.73
Payment Method     2579  25.79
Location           3265  32.65
Transaction Date    159   1.59

                  count      %
Item                333   3.33
Quantity            138   1.38
Price Per Unit      179   1.79
Total Spent         173   1.73
Payment Method     2579  25.79
Location           3265  32.65
Transaction Date    159   1.59

In [26]:
print("Unique value:\n")
print(df["Item"].value_counts(dropna=False))
print
print("--- Item ---\n")
print(df["Payment Method"].value_counts(dropna=False))
print("--- PAy Metod  ---\n")
print(df["Location"].value_counts(dropna=False))
print("--- Location ---\n")

Unique value:

Item
Juice       1171
Coffee      1165
Salad       1148
Cake        1139
Sandwich    1131
Smoothie    1096
Cookie      1092
Tea         1089
UNKNOWN      344
NaN          333
ERROR        292
Name: count, dtype: int64
--- Item ---

Payment Method
NaN               2579
Digital Wallet    2291
Credit Card       2273
Cash              2258
ERROR              306
UNKNOWN            293
Name: count, dtype: int64
--- PAy Metod  ---

Location
NaN         3265
Takeaway    3022
In-store    3017
ERROR        358
UNKNOWN      338
Name: count, dtype: int64
--- Location ---

In [32]:
print("Find lines with 'Error" or 'UNKNOW')
masr_er = df.isin(['ERROR', 'UNKNOWN']).any(axis=1).sum()
print(f"Number of lines with 'Error' or 'UNKNOWN': {masr_er}")

Find lines with 'Error
Number of lines with 'Error' or 'UNKNOWN': 2845

ДЗ True/False  замінити фицрами по кожному значенню